# Basics of Nummpy

In [2]:
import numpy as np

In [3]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [6]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
## Python List vs Numpy Array

In [11]:
py_arr = [1,2,3,4,5]
print(py_arr*2)

np_arr = np.array([1,2,3,4,5])
print(np_arr*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
